import { TestBed } from '@angular/core/testing';
import { provideHttpClient } from '@angular/common/http';
import { HttpTestingController, provideHttpClientTesting } from '@angular/common/http/testing';
import { environment } from '@env/environment';
import { PublishStatusService } from './publish-status.service';
import { PublishStatus, PublishStatusRequest } from './publish-status.model';

describe('PublishStatusService', () => {
  let service: PublishStatusService;
  let httpMock: HttpTestingController;

  const baseUrl = `${environment.apiBaseUrl}/publish-statuses`;

  const draft: PublishStatus = {
    pkid: 1,
    description: '草稿',
    isDraft: true,
    isPublished: false,
    isDiscontinued: false,
    courseCount: 0,
    promotionCount: 0
  };

  beforeEach(() => {
    TestBed.configureTestingModule({
      providers: [provideHttpClient(), provideHttpClientTesting()]
    });

    service = TestBed.inject(PublishStatusService);
    httpMock = TestBed.inject(HttpTestingController);
  });

  afterEach(() => httpMock.verify());

  it('GETs all statuses', () => {
    let result: PublishStatus[] | undefined;
    service.getAll().subscribe(statuses => (result = statuses));

    const req = httpMock.expectOne(baseUrl);
    expect(req.request.method).toBe('GET');
    req.flush([draft]);

    expect(result).toEqual([draft]);
  });

  it('POSTs the filter to /query', () => {
    let result: PublishStatus[] | undefined;
    service.query({ keyword: '草稿', isDraft: true, isPublished: null, isDiscontinued: null })
      .subscribe(r => (result = r));

    const req = httpMock.expectOne(`${baseUrl}/query`);
    expect(req.request.method).toBe('POST');
    expect(req.request.body).toEqual({ keyword: '草稿', isDraft: true, isPublished: null, isDiscontinued: null });
    req.flush([draft]);

    expect(result?.length).toBe(1);
  });

  it('GETs a single status by pkid', () => {
    let result: PublishStatus | undefined;
    service.getByPkid(1).subscribe(status => (result = status));

    const req = httpMock.expectOne(`${baseUrl}/1`);
    expect(req.request.method).toBe('GET');
    req.flush(draft);

    expect(result?.description).toBe('草稿');
  });

  it('POSTs a new status including the caller-supplied pkid', () => {
    const request: PublishStatusRequest = {
      pkid: 10,
      description: '審核中',
      isDraft: true,
      isPublished: false,
      isDiscontinued: false
    };

    let created: PublishStatus | undefined;
    service.create(request).subscribe(status => (created = status));

    const req = httpMock.expectOne(baseUrl);
    expect(req.request.method).toBe('POST');
    // pkid is not generated by the DB — it must travel in the create payload.
    expect(req.request.body.pkid).toBe(10);
    req.flush({ ...draft, pkid: 10, description: '審核中' });

    expect(created?.pkid).toBe(10);
  });

  it('PUTs an updated status with the pkid in the body (no route param)', () => {
    const request: PublishStatusRequest = {
      pkid: 2,
      description: '已發布',
      isDraft: false,
      isPublished: true,
      isDiscontinued: false
    };

    service.update(request).subscribe();

    const req = httpMock.expectOne(baseUrl);
    expect(req.request.method).toBe('PUT');
    expect(req.request.body.pkid).toBe(2);
    req.flush(null);
  });

  it('DELETEs a status by pkid', () => {
    service.delete(2).subscribe();

    const req = httpMock.expectOne(`${baseUrl}/2`);
    expect(req.request.method).toBe('DELETE');
    req.flush(null);
  });
});
