/** 原廠導覽物件 (Course.partner). */
export interface CourseNavPartner {
  pkid: number;
  name: string;
}

/** 課程群組導覽物件 (Course.courseGroup). */
export interface CourseNavCourseGroup {
  pkid: number;
  description: string;
}

/** 上架狀態導覽物件 (Course.publishStatus). */
export interface CourseNavPublishStatus {
  pkid: number;
  description: string;
}

/** 課程 (Course) — matches the API response model. */
export interface Course {
  pkid: number;
  title: string;
  officialTitle: string | null;
  courseId: string;
  prodCourseId: string;
  friendlyUrl: string;
  displayOrder: number;
  partnerPkid: number;
  courseGroupPkid: number | null;
  publishStatusPkid: number;
  scheduleOn: string;
  scheduleOff: string;
  hour: number;
  listPrice: number;
  learningCredit: number;
  material: string | null;
  objective: string | null;
  target: string | null;
  prerequisites: string | null;
  outline: string | null;
  towardCertOrExam: string | null;
  note: string | null;
  otherInfo: string | null;
  canRepeat: boolean;

  /** FK nav objects resolved by the API's multi-map JOIN. courseGroup is null when the FK is null. */
  partner: CourseNavPartner | null;
  courseGroup: CourseNavCourseGroup | null;
  publishStatus: CourseNavPublishStatus | null;

  /** Child-row counts. Any non-zero value means the API will refuse the delete with a 409. */
  courseFaqCount: number;
  certificationCount: number;
  jobCategoryCount: number;
  relatedLinkCount: number;
  hotCourseCount: number;
  recommCount: number;
}

/**
 * 課程新增／修改 DTO.
 * `pkid` is an int IDENTITY generated by the database: send 0 on create, and on update it identifies
 * the row (travelling in the body, never the route) and is not re-written. Dates are `yyyy-MM-dd`.
 */
export interface CourseRequest {
  pkid: number;
  title: string;
  officialTitle: string | null;
  courseId: string;
  prodCourseId: string;
  friendlyUrl: string;
  displayOrder: number;
  partnerPkid: number;
  courseGroupPkid: number | null;
  publishStatusPkid: number;
  scheduleOn: string;
  scheduleOff: string;
  hour: number;
  listPrice: number;
  learningCredit: number;
  material: string | null;
  objective: string | null;
  target: string | null;
  prerequisites: string | null;
  outline: string | null;
  towardCertOrExam: string | null;
  note: string | null;
  otherInfo: string | null;
  canRepeat: boolean;
}

/** 課程查詢條件. `canRepeat` is tri-state: null = 不篩選. */
export interface CourseQuery {
  keyword?: string | null;
  partnerPkid?: number | null;
  courseGroupPkid?: number | null;
  publishStatusPkid?: number | null;
  scheduleOnFrom?: string | null;
  scheduleOnTo?: string | null;
  scheduleOffFrom?: string | null;
  scheduleOffTo?: string | null;
  canRepeat?: boolean | null;
}
