/** 訓練中心導覽物件 (FeaturedPromoItem.trainingCenter). */
export interface FeaturedPromoNavTrainingCenter {
  pkid: number;
  name: string;
}

/** 促銷導覽物件 (FeaturedPromoItem.promotion). 列表以 promoCode 呈現 promotionPkid. */
export interface FeaturedPromoNavPromotion {
  pkid: number;
  promoCode: string;
}

/** 首頁上稿項目 (FeaturedPromoItem) — matches the API response model. */
export interface FeaturedPromoItem {
  pkid: number;
  scheduleOn: string;
  trainingCenterPkid: number;
  slot: number;
  promotionPkid: number;
  topic: string;
  description: string;

  /** FK nav objects resolved by the API's multi-map JOIN. Both FKs are NOT NULL, so neither is null. */
  trainingCenter: FeaturedPromoNavTrainingCenter | null;
  promotion: FeaturedPromoNavPromotion | null;
}

/**
 * 上稿新增／修改 DTO.
 * `pkid` is an int IDENTITY generated by the database: send 0 on create, and on update it identifies
 * the row (travelling in the body, never the route) and is not re-written. `scheduleOn` is `yyyy-MM-dd`.
 */
export interface FeaturedPromoItemRequest {
  pkid: number;
  scheduleOn: string;
  trainingCenterPkid: number;
  slot: number;
  promotionPkid: number;
  topic: string;
  description: string;
}

/** 上稿查詢條件. The scheduler filters by TrainingCenter tab + one-week ScheduleOn range. */
export interface FeaturedPromoItemQuery {
  trainingCenterPkid?: number | null;
  scheduleOnFrom?: string | null;
  scheduleOnTo?: string | null;
  slot?: number | null;
  keyword?: string | null;
}

/** Slot move direction: `down` = slot +1 (＋ button), `up` = slot −1 (－ button). */
export type MoveDirection = 'up' | 'down';

/** 訓練中心下拉／分頁資料 (/api/lookups/training-centers). */
export interface TrainingCenterLookup {
  pkid: number;
  name: string;
  displayOrder: number;
}

/** 促銷下拉／查詢資料 (/api/lookups/promo-codes) — resolves an entered PromoCode to its pkid. */
export interface PromotionLookup {
  pkid: number;
  promoCode: string;
  topic: string;
  description: string;
}
