using CMS.API.Data;
using CMS.API.Models;
using Dapper;

namespace CMS.API.Repositories;

public class CourseGroupRepository(IDbConnectionFactory connectionFactory) : ICourseGroupRepository
{
    // CourseGroup has no FK columns, so there is nothing to multi-map. The two counts are the delete
    // guard: the controller reads them off the entity it already loaded for its 404. CourseCount matters
    // more than the usual count column — FK_Course_CourseGroup cascades, so nothing else stops the delete.
    private const string SelectColumns = """
        SELECT cg.pkid, cg.Description,
               (SELECT COUNT(*) FROM Course c             WHERE c.CourseGroup_pkid = cg.pkid) AS CourseCount,
               (SELECT COUNT(*) FROM PartnerCourseGroup p WHERE p.CourseGroup_pkid = cg.pkid) AS PartnerCourseGroupCount
        FROM CourseGroup cg
        """;

    // No DisplayOrder column, and pkid is a meaningless IDENTITY (unlike PublishStatus, whose pkid is a
    // hand-assigned code). Description ASC is what a user scanning the lookup dropdown expects; pkid breaks
    // ties, since the schema permits two groups to share a description.
    private const string OrderBy = " ORDER BY cg.Description ASC, cg.pkid ASC";

    public async Task<IEnumerable<CourseGroup>> GetAllAsync()
    {
        using var conn = connectionFactory.CreateConnection();
        return await conn.QueryAsync<CourseGroup>($"{SelectColumns}{OrderBy}");
    }

    public async Task<IEnumerable<CourseGroup>> QueryAsync(CourseGroupQuery query)
    {
        var where = new List<string>();
        var parameters = new DynamicParameters();

        if (!string.IsNullOrWhiteSpace(query.Keyword))
        {
            where.Add("cg.Description LIKE @Keyword");
            parameters.Add("Keyword", $"%{query.Keyword.Trim()}%");
        }

        var sql = SelectColumns
            + (where.Count > 0 ? " WHERE " + string.Join(" AND ", where) : string.Empty)
            + OrderBy;

        using var conn = connectionFactory.CreateConnection();
        return await conn.QueryAsync<CourseGroup>(sql, parameters);
    }

    public async Task<CourseGroup?> GetByPkidAsync(short pkid)
    {
        using var conn = connectionFactory.CreateConnection();
        return await conn.QuerySingleOrDefaultAsync<CourseGroup>(
            $"{SelectColumns} WHERE cg.pkid = @Pkid", new { Pkid = pkid });
    }

    /// <summary>pkid is a smallint IDENTITY — generated by SQL Server, never sent by the caller.</summary>
    public async Task<short> CreateAsync(CourseGroupRequest request)
    {
        const string sql = """
            INSERT INTO CourseGroup (Description)
            VALUES (@Description);
            SELECT CAST(SCOPE_IDENTITY() AS smallint);
            """;

        using var conn = connectionFactory.CreateConnection();
        return await conn.ExecuteScalarAsync<short>(sql, request);
    }

    /// <summary>Description is the only writable column — children reference pkid, so nothing is immutable.</summary>
    public async Task<bool> UpdateAsync(CourseGroupRequest request)
    {
        const string sql = """
            UPDATE CourseGroup
            SET Description = @Description
            WHERE pkid = @Pkid;
            """;

        using var conn = connectionFactory.CreateConnection();
        return await conn.ExecuteAsync(sql, request) > 0;
    }

    /// <summary>
    /// Unguarded, and dangerous on its own: FK_Course_CourseGroup is ON DELETE CASCADE, so SQL Server
    /// deletes every Course in the group (and, via their own cascades, their CourseInCertification and
    /// CourseJobCategories rows) instead of rejecting. CourseGroupsController.Delete checks the counts first.
    /// </summary>
    public async Task<bool> DeleteAsync(short pkid)
    {
        using var conn = connectionFactory.CreateConnection();
        return await conn.ExecuteAsync("DELETE FROM CourseGroup WHERE pkid = @Pkid", new { Pkid = pkid }) > 0;
    }
}
