using System.Data;
using CMS.API.Auditing;
using CMS.API.Data;
using CMS.API.Models;
using Dapper;

namespace CMS.API.Repositories;

public class FeaturedPromoItemRepository(IDbConnectionFactory connectionFactory, RowAuditWriter auditWriter) : IFeaturedPromoItemRepository
{
    private const string TableName = "FeaturedPromoItem";

    // Two outbound FKs (TrainingCenter, Promotion2), both NOT NULL → two INNER JOINs and two nav objects.
    // All FeaturedPromoItem columns come first, then TrainingCenter (pkid, Name), then Promotion2
    // (pkid, PromoCode). splitOn = "pkid,pkid" marks the start of each nav object.
    // No nchar columns here (Name/PromoCode are nvarchar), so no RTRIM needed.
    private const string SelectColumns = """
        SELECT f.pkid, f.ScheduleOn, f.TrainingCenter_pkid AS TrainingCenterPkid, f.Slot,
               f.Promotion_pkid AS PromotionPkid, f.Topic, f.Description,
               tc.pkid, tc.Name,
               pr.pkid, pr.PromoCode
        FROM FeaturedPromoItem f
        JOIN TrainingCenter tc ON tc.pkid = f.TrainingCenter_pkid
        JOIN Promotion2 pr     ON pr.pkid = f.Promotion_pkid
        """;

    // The scheduler reads the grid day-by-day then slot-by-slot, so that is the natural order.
    private const string OrderBy = " ORDER BY f.ScheduleOn ASC, f.TrainingCenter_pkid ASC, f.Slot ASC";

    private const string SplitOn = "pkid,pkid";

    private static FeaturedPromoItem Map(FeaturedPromoItem item, FeaturedPromoNavTrainingCenter tc, FeaturedPromoNavPromotion promo)
    {
        item.TrainingCenter = tc;
        item.Promotion = promo;
        return item;
    }

    public async Task<IEnumerable<FeaturedPromoItem>> GetAllAsync()
    {
        using var conn = connectionFactory.CreateConnection();
        return await conn.QueryAsync<FeaturedPromoItem, FeaturedPromoNavTrainingCenter, FeaturedPromoNavPromotion, FeaturedPromoItem>(
            $"{SelectColumns}{OrderBy}", Map, splitOn: SplitOn);
    }

    public async Task<IEnumerable<FeaturedPromoItem>> QueryAsync(FeaturedPromoItemQuery query)
    {
        var where = new List<string>();
        var parameters = new DynamicParameters();

        if (query.TrainingCenterPkid.HasValue)
        {
            where.Add("f.TrainingCenter_pkid = @TrainingCenterPkid");
            parameters.Add("TrainingCenterPkid", query.TrainingCenterPkid.Value);
        }

        if (query.ScheduleOnFrom.HasValue)
        {
            where.Add("f.ScheduleOn >= @ScheduleOnFrom");
            parameters.Add("ScheduleOnFrom", query.ScheduleOnFrom.Value);
        }

        if (query.ScheduleOnTo.HasValue)
        {
            where.Add("f.ScheduleOn <= @ScheduleOnTo");
            parameters.Add("ScheduleOnTo", query.ScheduleOnTo.Value);
        }

        if (query.Slot.HasValue)
        {
            where.Add("f.Slot = @Slot");
            parameters.Add("Slot", query.Slot.Value);
        }

        if (!string.IsNullOrWhiteSpace(query.Keyword))
        {
            where.Add("(f.Topic LIKE @Keyword OR f.Description LIKE @Keyword OR pr.PromoCode LIKE @Keyword)");
            parameters.Add("Keyword", $"%{query.Keyword.Trim()}%");
        }

        var sql = SelectColumns
            + (where.Count > 0 ? " WHERE " + string.Join(" AND ", where) : string.Empty)
            + OrderBy;

        using var conn = connectionFactory.CreateConnection();
        return await conn.QueryAsync<FeaturedPromoItem, FeaturedPromoNavTrainingCenter, FeaturedPromoNavPromotion, FeaturedPromoItem>(
            sql, Map, parameters, splitOn: SplitOn);
    }

    public async Task<FeaturedPromoItem?> GetByPkidAsync(int pkid)
    {
        using var conn = connectionFactory.CreateConnection();
        var rows = await conn.QueryAsync<FeaturedPromoItem, FeaturedPromoNavTrainingCenter, FeaturedPromoNavPromotion, FeaturedPromoItem>(
            $"{SelectColumns} WHERE f.pkid = @Pkid", Map, new { Pkid = pkid }, splitOn: SplitOn);
        return rows.SingleOrDefault();
    }

    public async Task<bool> SlotTakenAsync(DateOnly scheduleOn, short trainingCenterPkid, byte slot, int excludePkid)
    {
        const string sql = """
            SELECT COUNT(*) FROM FeaturedPromoItem
            WHERE ScheduleOn = @ScheduleOn
              AND TrainingCenter_pkid = @TrainingCenterPkid
              AND Slot = @Slot
              AND pkid <> @ExcludePkid
            """;

        using var conn = connectionFactory.CreateConnection();
        return await conn.ExecuteScalarAsync<int>(sql, new
        {
            ScheduleOn = scheduleOn,
            TrainingCenterPkid = trainingCenterPkid,
            Slot = slot,
            ExcludePkid = excludePkid
        }) > 0;
    }

    /// <summary>pkid is an int IDENTITY — generated by SQL Server, never sent by the caller.</summary>
    public async Task<int> CreateAsync(FeaturedPromoItemRequest request)
    {
        const string sql = """
            INSERT INTO FeaturedPromoItem (ScheduleOn, TrainingCenter_pkid, Slot, Promotion_pkid, Topic, Description)
            VALUES (@ScheduleOn, @TrainingCenterPkid, @Slot, @PromotionPkid, @Topic, @Description);
            SELECT CAST(SCOPE_IDENTITY() AS int);
            """;

        using var conn = connectionFactory.CreateConnection();
        conn.Open();
        using var tx = conn.BeginTransaction();

        var pkid = await conn.ExecuteScalarAsync<int>(sql, request, tx);
        var created = await LoadByPkidAsync(conn, pkid, tx);
        await auditWriter.LogInsertAsync(TableName, created!, conn, tx);

        tx.Commit();
        return pkid;
    }

    public async Task<bool> UpdateAsync(FeaturedPromoItemRequest request)
    {
        const string sql = """
            UPDATE FeaturedPromoItem
            SET ScheduleOn = @ScheduleOn,
                TrainingCenter_pkid = @TrainingCenterPkid,
                Slot = @Slot,
                Promotion_pkid = @PromotionPkid,
                Topic = @Topic,
                Description = @Description
            WHERE pkid = @Pkid;
            """;

        using var conn = connectionFactory.CreateConnection();
        conn.Open();
        using var tx = conn.BeginTransaction();

        var before = await LoadByPkidAsync(conn, request.Pkid, tx);
        if (before is null)
        {
            return false;
        }

        await conn.ExecuteAsync(sql, request, tx);
        var after = await LoadByPkidAsync(conn, request.Pkid, tx);
        await auditWriter.LogUpdateAsync(TableName, before, after!, conn, tx);

        tx.Commit();
        return true;
    }

    /// <summary>Nothing FKs to FeaturedPromoItem, so the delete is unguarded — no child rows to protect.</summary>
    public async Task<bool> DeleteAsync(int pkid)
    {
        using var conn = connectionFactory.CreateConnection();
        conn.Open();
        using var tx = conn.BeginTransaction();

        var row = await LoadByPkidAsync(conn, pkid, tx);
        if (row is null)
        {
            return false;
        }

        await conn.ExecuteAsync("DELETE FROM FeaturedPromoItem WHERE pkid = @Pkid", new { Pkid = pkid }, tx);
        await auditWriter.LogDeleteAsync(TableName, row, conn, tx);

        tx.Commit();
        return true;
    }

    /// <summary>Loads a row (with nav objects) on an existing open connection/transaction (see PublishStatusRepository).</summary>
    private static async Task<FeaturedPromoItem?> LoadByPkidAsync(IDbConnection conn, int pkid, IDbTransaction tx)
    {
        var rows = await conn.QueryAsync<FeaturedPromoItem, FeaturedPromoNavTrainingCenter, FeaturedPromoNavPromotion, FeaturedPromoItem>(
            $"{SelectColumns} WHERE f.pkid = @Pkid", Map, new { Pkid = pkid }, tx, splitOn: SplitOn);
        return rows.SingleOrDefault();
    }

    public async Task<MoveResult> MoveAsync(int pkid, bool down)
    {
        using var conn = connectionFactory.CreateConnection();
        conn.Open();

        var item = (await conn.QueryAsync<FeaturedPromoItem>(
            "SELECT pkid, ScheduleOn, TrainingCenter_pkid AS TrainingCenterPkid, Slot FROM FeaturedPromoItem WHERE pkid = @Pkid",
            new { Pkid = pkid })).SingleOrDefault();

        if (item is null)
        {
            return MoveResult.NotFound;
        }

        var target = down ? item.Slot + 1 : item.Slot - 1;
        if (target < 1 || target > 3)
        {
            return MoveResult.OutOfRange;
        }

        using var tx = conn.BeginTransaction();

        var siblingPkid = await conn.ExecuteScalarAsync<int?>(
            "SELECT pkid FROM FeaturedPromoItem WHERE ScheduleOn = @S AND TrainingCenter_pkid = @Tc AND Slot = @Slot",
            new { S = item.ScheduleOn, Tc = item.TrainingCenterPkid, Slot = (byte)target }, tx);

        if (siblingPkid is int sibling)
        {
            // Swap the two rows. Park the sibling at slot 0 first so the UNIQUE index is never violated
            // mid-swap (0 is outside the valid 1-3 range, so it can never collide with a real slot).
            await conn.ExecuteAsync("UPDATE FeaturedPromoItem SET Slot = 0 WHERE pkid = @P", new { P = sibling }, tx);
            await conn.ExecuteAsync("UPDATE FeaturedPromoItem SET Slot = @T WHERE pkid = @P", new { T = (byte)target, P = pkid }, tx);
            await conn.ExecuteAsync("UPDATE FeaturedPromoItem SET Slot = @T WHERE pkid = @P", new { T = item.Slot, P = sibling }, tx);
        }
        else
        {
            await conn.ExecuteAsync("UPDATE FeaturedPromoItem SET Slot = @T WHERE pkid = @P", new { T = (byte)target, P = pkid }, tx);
        }

        tx.Commit();
        return MoveResult.Moved;
    }
}
