using System.Data;
using CMS.API.Auditing;
using CMS.API.Data;
using CMS.API.Models;
using Dapper;

namespace CMS.API.Repositories;

public class PartnerRepository(IDbConnectionFactory connectionFactory, RowAuditWriter auditWriter) : IPartnerRepository
{
    private const string TableName = "Partner";

    // Partner has no FK columns, so there is nothing to multi-map. The five counts are the
    // delete guard: the controller reads them off the entity it already loaded for its 404.
    // Seminar has no FK constraint in the schema, but a delete would still orphan its rows.
    private const string SelectColumns = """
        SELECT p.pkid, p.Name, p.AppKey, p.NameOnPartnerMenu, p.NameOnCourseDetailPage,
               p.DisplayOrder, p.ImageFilename,
               (SELECT COUNT(*) FROM Course c             WHERE c.Partner_pkid = p.pkid)        AS CourseCount,
               (SELECT COUNT(*) FROM Certification ct     WHERE ct.Partner_pkid = p.pkid)       AS CertificationCount,
               (SELECT COUNT(*) FROM PartnerCourseGroup g WHERE g.Partner_pkid = p.pkid)        AS CourseGroupCount,
               (SELECT COUNT(*) FROM Promotion2 m         WHERE m.RelatedPartner_pkid = p.pkid) AS PromotionCount,
               (SELECT COUNT(*) FROM Seminar s            WHERE s.Partner_pkid = p.pkid)        AS SeminarCount
        FROM Partner p
        """;

    private const string OrderBy = " ORDER BY p.DisplayOrder ASC, p.pkid ASC";

    public async Task<IEnumerable<Partner>> GetAllAsync()
    {
        using var conn = connectionFactory.CreateConnection();
        return await conn.QueryAsync<Partner>($"{SelectColumns}{OrderBy}");
    }

    public async Task<IEnumerable<Partner>> QueryAsync(PartnerQuery query)
    {
        var where = new List<string>();
        var parameters = new DynamicParameters();

        if (!string.IsNullOrWhiteSpace(query.Keyword))
        {
            where.Add("""
                (p.Name LIKE @Keyword
                 OR p.AppKey LIKE @Keyword
                 OR p.NameOnPartnerMenu LIKE @Keyword
                 OR p.NameOnCourseDetailPage LIKE @Keyword)
                """);
            parameters.Add("Keyword", $"%{query.Keyword.Trim()}%");
        }

        if (query.DisplayOrderFrom.HasValue)
        {
            where.Add("p.DisplayOrder >= @DisplayOrderFrom");
            parameters.Add("DisplayOrderFrom", query.DisplayOrderFrom.Value);
        }

        if (query.DisplayOrderTo.HasValue)
        {
            where.Add("p.DisplayOrder <= @DisplayOrderTo");
            parameters.Add("DisplayOrderTo", query.DisplayOrderTo.Value);
        }

        if (query.HasImage.HasValue)
        {
            where.Add(query.HasImage.Value
                ? "p.ImageFilename IS NOT NULL"
                : "p.ImageFilename IS NULL");
        }

        var sql = SelectColumns
            + (where.Count > 0 ? " WHERE " + string.Join(" AND ", where) : string.Empty)
            + OrderBy;

        using var conn = connectionFactory.CreateConnection();
        return await conn.QueryAsync<Partner>(sql, parameters);
    }

    public async Task<Partner?> GetByPkidAsync(short pkid)
    {
        using var conn = connectionFactory.CreateConnection();
        return await conn.QuerySingleOrDefaultAsync<Partner>(
            $"{SelectColumns} WHERE p.pkid = @Pkid", new { Pkid = pkid });
    }

    /// <summary>pkid is a smallint IDENTITY — generated by SQL Server, never sent by the caller.</summary>
    public async Task<short> CreateAsync(PartnerRequest request)
    {
        const string sql = """
            INSERT INTO Partner (Name, AppKey, NameOnPartnerMenu, NameOnCourseDetailPage, DisplayOrder, ImageFilename)
            VALUES (@Name, @AppKey, @NameOnPartnerMenu, @NameOnCourseDetailPage, @DisplayOrder, @ImageFilename);
            SELECT CAST(SCOPE_IDENTITY() AS smallint);
            """;

        using var conn = connectionFactory.CreateConnection();
        conn.Open();
        using var tx = conn.BeginTransaction();

        var pkid = await conn.ExecuteScalarAsync<short>(sql, request, tx);
        var created = await LoadByPkidAsync(conn, pkid, tx);
        await auditWriter.LogInsertAsync(TableName, created!, conn, tx);

        tx.Commit();
        return pkid;
    }

    /// <summary>Every non-key column is writable — nothing foreign-keys to AppKey, so it is not immutable.</summary>
    public async Task<bool> UpdateAsync(PartnerRequest request)
    {
        const string sql = """
            UPDATE Partner
            SET Name = @Name,
                AppKey = @AppKey,
                NameOnPartnerMenu = @NameOnPartnerMenu,
                NameOnCourseDetailPage = @NameOnCourseDetailPage,
                DisplayOrder = @DisplayOrder,
                ImageFilename = @ImageFilename
            WHERE pkid = @Pkid;
            """;

        using var conn = connectionFactory.CreateConnection();
        conn.Open();
        using var tx = conn.BeginTransaction();

        var before = await LoadByPkidAsync(conn, request.Pkid, tx);
        if (before is null)
        {
            return false;
        }

        await conn.ExecuteAsync(sql, request, tx);
        var after = await LoadByPkidAsync(conn, request.Pkid, tx);
        await auditWriter.LogUpdateAsync(TableName, before, after!, conn, tx);

        tx.Commit();
        return true;
    }

    public async Task<bool> DeleteAsync(short pkid)
    {
        using var conn = connectionFactory.CreateConnection();
        conn.Open();
        using var tx = conn.BeginTransaction();

        var row = await LoadByPkidAsync(conn, pkid, tx);
        if (row is null)
        {
            return false;
        }

        await conn.ExecuteAsync("DELETE FROM Partner WHERE pkid = @Pkid", new { Pkid = pkid }, tx);
        await auditWriter.LogDeleteAsync(TableName, row, conn, tx);

        tx.Commit();
        return true;
    }

    /// <summary>Loads a row on an existing open connection/transaction (see PublishStatusRepository).</summary>
    private static async Task<Partner?> LoadByPkidAsync(IDbConnection conn, short pkid, IDbTransaction tx)
        => await conn.QuerySingleOrDefaultAsync<Partner>(
            $"{SelectColumns} WHERE p.pkid = @Pkid", new { Pkid = pkid }, tx);
}
