/** 合作夥伴 (Partner) — matches the API response model. */
export interface Partner {
  pkid: number;
  name: string;
  appKey: string;
  nameOnPartnerMenu: string;
  nameOnCourseDetailPage: string;
  displayOrder: number;
  imageFilename: string | null;

  /** Child-row counts. Non-zero on any of them means the API will refuse the delete with a 409. */
  courseCount: number;
  certificationCount: number;
  courseGroupCount: number;
  promotionCount: number;
  seminarCount: number;
}

/**
 * 合作夥伴新增／修改 DTO.
 * `pkid` is a smallint IDENTITY generated by the database: send 0 on create, and on update it
 * identifies the row (travelling in the body, never the route) and is not re-written.
 */
export interface PartnerRequest {
  pkid: number;
  name: string;
  appKey: string;
  nameOnPartnerMenu: string;
  nameOnCourseDetailPage: string;
  displayOrder: number;
  imageFilename: string | null;
}

/** 合作夥伴查詢條件. `hasImage` is tri-state: null = 不篩選. */
export interface PartnerQuery {
  keyword?: string | null;
  displayOrderFrom?: number | null;
  displayOrderTo?: number | null;
  hasImage?: boolean | null;
}
